services:
  sophia:
    build:
      context: .
      target: base
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sophia.rule=Host(`sophia.localhost`)"
      - "traefik.http.services.sophia.loadbalancer.server.port=80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/code
      - /code/src/Sophia.Api/bin
      - /code/src/Sophia.Api/obj
      - /code/src/Sophia.Domain/bin
      - /code/src/Sophia.Domain/obj
      - /code/src/Sophia.Infrastructure/bin
      - /code/src/Sophia.Infrastructure/obj
      - /code/src/Sophia.Db/bin
      - /code/src/Sophia.Db/obj
    networks:
      - default
      - docker_default
    command:
      [
        "dotnet",
        "watch",
        "--non-interactive",
        "run",
        "--project",
        "src/Sophia.Api",
        "--urls",
        "http://0.0.0.0:80",
      ]
  db:
    image: mysql:9.1.0
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/0.sql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - "3306:3306"
    networks:
      - default
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

volumes:
  db-store:

networks:
  docker_default:
    external: true
    name: docker_default
