services:
  sophia:
    build:
      context: .
      target: base
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sophia.rule=Host(`sophia.localhost`)"
      - "traefik.http.services.sophia.loadbalancer.server.port=80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    volumes:
      - .:/code
      - /code/src/Sophia.Api/bin
      - /code/src/Sophia.Api/obj
      - /code/src/Sophia.Domain/bin
      - /code/src/Sophia.Domain/obj
      - /code/src/Sophia.Infrastructure/bin
      - /code/src/Sophia.Infrastructure/obj
      - /code/src/Sophia.Db/bin
      - /code/src/Sophia.Db/obj
    networks:
      - default
      - docker_default
    command:
      [
        "dotnet",
        "watch",
        "--non-interactive",
        "run",
        "--project",
        "src/Sophia.Api",
        "--urls",
        "http://0.0.0.0:80",
      ]
  db:
    image: postgres:17
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/0.sql
    environment:
      - POSTGRES_DB=sophia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    networks:
      - default
    labels:
      - "traefik.enable=false"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]

volumes:
  db-store:

networks:
  docker_default:
    external: true
    name: docker_default
