version: '3'

tasks:
  build:
    cmd: docker compose exec sophia dotnet build

  exec:
    cmd: docker compose exec sophia dotnet exec

  docker_build:
    desc: Build the Docker images without cache
    cmd: docker compose build --pull --no-cache

  up:
    desc: Start the services defined in compose.yaml
    cmd: docker compose up -d

  stop:
    desc: Stop the services defined in compose.yaml
    cmd: docker compose stop

  down:
    desc: Stop and remove the containers
    cmd: docker compose down

  bash:
    desc: exec bash
    cmd: docker compose exec sophia bash

  migrate:
    desc: Run the migrations
    cmds:
      - docker compose exec sophia bash -c "cd /code/src/Sophia.Db && dotnet ef database update"

  codegen:
    desc: Generate Lily API client from OpenAPI spec
    cmds:
      - cd src/Sophia.Infrastructure/Lily && dotnet nswag run nswag.json
