// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sophia.Api.DbContext;

#nullable disable

namespace Sophia.Api.Migrations
{
    [DbContext(typeof(SophiaContext))]
    [Migration("20250411094432_FixColumnNameForUser")]
    partial class FixColumnNameForUser
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sophia.Api.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<ulong>("DiscordUserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("discord_user_id")
                        .HasComment("ユーザーID");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("icon_url")
                        .HasComment("アイコンURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("名前");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password")
                        .HasComment("パスワード");

                    b.Property<bool>("Status")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("status")
                        .HasComment("ステータス");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("DiscordUserId")
                        .IsUnique()
                        .HasDatabaseName("ix_users_discord_user_id");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
