// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sophia.Infrastructure.DbContext;

#nullable disable

namespace Sophia.Db.Migrations
{
    [DbContext(typeof(SophiaContext))]
    [Migration("20260323152641_FixSeederTimestamps")]
    partial class FixSeederTimestamps
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sophia.Infrastructure.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Auth0Sub")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("auth0sub")
                        .HasComment("Auth0 sub");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<string>("DiscordUserId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("discord_user_id")
                        .HasComment("Discord User ID");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("icon_url")
                        .HasComment("アイコンURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("名前");

                    b.Property<int>("Status")
                        .HasMaxLength(255)
                        .HasColumnType("int")
                        .HasColumnName("status")
                        .HasComment("ステータス");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Auth0Sub")
                        .IsUnique()
                        .HasDatabaseName("ix_users_auth0sub");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Auth0Sub = "auth0|test-user-1",
                            CreatedAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconUrl = "",
                            Name = "山根綺",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2L,
                            Auth0Sub = "auth0|test-user-2",
                            CreatedAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc),
                            IconUrl = "",
                            Name = "桑原由気",
                            Status = 0,
                            UpdatedAt = new DateTime(2026, 3, 21, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
