// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sophia.Infrastructure.DbContext;

#nullable disable

namespace Sophia.Db.Migrations
{
    [DbContext(typeof(SophiaContext))]
    partial class SophiaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Sophia.Infrastructure.Models.AdminUser", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<string>("Emai")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("emai")
                        .HasComment("メールアドレス");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("名前");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("role")
                        .HasComment("ロール");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status")
                        .HasComment("ステータス");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id")
                        .HasName("pk_admin_user");

                    b.ToTable("admin_user", (string)null);
                });

            modelBuilder.Entity("Sophia.Infrastructure.Models.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<string>("Emai")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("emai")
                        .HasComment("メールアドレス");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("icon_url")
                        .HasComment("アイコンURL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("name")
                        .HasComment("名前");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("status")
                        .HasComment("ステータス");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Emai")
                        .IsUnique()
                        .HasDatabaseName("ix_users_emai");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Sophia.Infrastructure.Models.UserDefinitiveRegisterToken", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<ulong>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at")
                        .HasComment("作成日時");

                    b.Property<DateTime>("ExpiredAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("expired_at")
                        .HasComment("有効期限");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_verified");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("token")
                        .HasComment("トークン");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at")
                        .HasComment("更新日時");

                    b.Property<ulong>("UserId")
                        .HasColumnType("bigint unsigned")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_definitive_register_token");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_definitive_register_token_user_id");

                    b.ToTable("user_definitive_register_token", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
